# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default  
  adapter: postgresql
  encoding: unicode  
  pool: 5  
  timeout: 5000  

development:  
  <<: *default  
  database: todolist_development
  username: postgres  
  password: 

test:  
  <<: *default  
  database: todolist_test  
  username: postgres  
  password:   

production:  
  <<: *default  
  database: todolist_production
  username: postgres  
  password: 
